#!/bin/bash
# ========================================
#	HEADER
# ========================================

# Author: Indranil Sen
#
# This bash program is a wrapper around
# the cd (chdir - Change Directory) command
# that enhances and expedites traversing
# deep directories.

# ========================================
#	VARIABLES
# ========================================

VERSION="1.0.0"
scriptName="${BASH_SOURCE[0]}"
scriptPath="$(cd "$(dirname "scriptName" )" && pwd)"
validDirectory=1

# ========================================
#	ARGUMENTS & FLAGS
# ========================================

if [ $# -eq 0 ]; then
    echo 'No argument'
fi

while [ ! $# -eq 0 ]; do
case "$1" in
    --help | -h)
    		echo -n -e "\ncdx [OPTIONS]... [DIRECTORY]...

        Change current directory to specified argument directory with logic
        built in to expedite traversing deep directories.

    	Options:
    	-h, --help                       Print usage information
    	-v, --version                    Prints version to standard output
        \n"
    		exit
    		;;
	--version | -v)
		echo "$VERSION"
		exit
		;;
    *)
        DIRECTORY="${1}"
		if [ ! -d "$DIRECTORY" ]; then
            validDirectory=0
			echo "$DIRECTORY: No such file or directory; $validDirectory"
			exit
		fi
        ;;
esac
shift
done
